### ISSUE TITLE
Motion speed should be FPS-invariant

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#1]
https://github.com/skejeton/save-game/blob/49f8a6a9de381b3e4ff379e84dff3c86379ff6c8/src/d_game.um#L178-L179

On my machine, the actual frame rate is about 20 FPS. Due to this, walking and jumping is very slow (like Apollo astronauts on the Moon). 

To fix this, the position updates should involve `th.delta`, just as the conventional kinematics formulae require. If you don't want to adjust speed values throughout the code, you can use a scale factor directly in the formulae (I suppose the nominal frame rate to be 60 FPS):
```
  ent.rect.x += ent.vel.x * th.delta / (1000.0 / 60.0)
  ent.rect.y += ent.vel.y * th.delta / (1000.0 / 60.0)
```
The same should also apply to accelerations:
```
ent.vel.y += 0.1 * th.delta / (1000.0 / 60.0)
```

**Comment by skejeton** [comment]
@vtereshkov I noticed that before this issue. That's been fixed!
