### ISSUE TITLE
Wrong keyboard focus in web builds on `itch.io`

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#19]
The SaveScum [web page](https://skejeton.itch.io/savescum) mentions the following problem: `IF THE INPUTS DON'T WORK TRY REBOOTING THE PAGE OR DISABLING THE ADBLOCKER`. It happens for me every time I load the page. Not that the controls literally "don't work", but they have a wrong focus (e.g., the up/down arrow keys scroll the whole page).

Is [this discussion](https://www.reddit.com/r/gamemaker/comments/kfs5cs/keyboard_inputs_no_longer_working_in_html5_game/) in any way relevant to our problem? What if we insert `window.focus()` somewhere in `shell.html`?

**Comment by skejeton** [comment]
Fixed by using focus!
