### ISSUE TITLE
Drawing optimizations

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#3]
When drawing the background, you can move the heavy arithmetic out of the inner loop. Also you can skip the background tiles that are outside the field of view.

When I replaced the background drawing algorithm with the following one, I got the frame rate increase from 19 to 33 FPS:
```
  scale := th.Vf2{d_global.screen.w/screen.w, d_global.screen.h/screen.h}.mulf(0.5)

  step := imgRocks.getDims().mul(scale)
  pos0 := th.Vf2{-16, -16}.mul(step).sub(screen.getPos().divf(4))

  for pos := pos0; pos.x < d_global.screen.w; pos.x += step.x {
    if pos.x + step.x < 0 {continue}
    pos.y = pos0.y
    for pos.y < d_global.screen.h; pos.y += step.y {
      if pos.y + step.y < 0 {continue}
      imgRocks.draw(th.Transform{p: pos, s: scale})    
    }
  } 
```
I expect that the world drawing logic can also be optimized.

**Comment by vtereshkov** [comment]
@skejeton What makes me think that the world drawing can be efficiently optimized if that only 1% to 18% inner loop iterations in `World.drawLayer()` are non-idle, i. e., have `tileId > 0`.

**Comment by skejeton** [comment]
@vtereshkov oh dear! thank you. I decided to write it in a very naive way because I just wanted to push the demo, and since forgot about it.

**Comment by skejeton** [comment]
> @skejeton What makes me think that the world drawing can be efficiently optimized if that only 1% to 18% inner loop iterations in `World.drawLayer()` are non-idle, i. e., have `tileId > 0`.

Yep. But even better world drawing optimization is just rendering only the tiles you can see on screen, that way you can have pretty much constant time.

**Comment by skejeton** [comment]
I'll implement world rendering which should render only tiles you see on screen right now, @vtereshkov I advise to record the FPS right now and then compare it with the new FPS.

**Comment by vtereshkov** [comment]
52...55 FPS after background rendering optimization.

**Comment by skejeton** [comment]
Yowza! Great. I think I'll do the world optimization now and it should be lovely

**Comment by skejeton** [comment]
@vtereshkov check out new optimizations and say what you think. I don't think there's much more drawing optimizations I can make yet, so I'll close this issue if you acknowledge it works. Thanks :P

**Comment by vtereshkov** [comment]
Perfect! Now it's 250 FPS in the play mode and 70 FPS in the editor mode when the frame rate limiter is off. 

However, when the limiter is set to 60 FPS, there are problems, as the actual time delta is 32 ms, while `th.delta` is 16 ms, so the walking and jumping are again very slow. I think it may be a problem with `sleep()` and timer resolution.

As this problem is in no way related to rendering performance, let's close the current issue.
