### ISSUE TITLE
Resizing the window makes the game hang on Windows

### ISSUE THREAD

**Issue by vtereshkov** [skejeton/save-game#6]
This doesn't happen on Linux. Nor does it happen in the editor mode on Windows.

**Comment by skejeton** [comment]
Weird. Can you DM me the tophat windows executable? I can't build it but I can run it through wine.

**Comment by vtereshkov** [comment]
[tophat.zip](https://github.com/skejeton/save-game/files/9595355/tophat.zip)

This is the latest version of tophat built with a cross-compiler. When I run the latest version of the game with it, I see a runtime error rather than hanging:
```
error: C:/Users/vtere/Desktop/save-game/src/d_world.um (139): Index -83 is out of range 0...39

        Stack trace:
                00008808: drawChunk
                00009066: ^World.drawLayer
                00018187: draw
                00024471: ^GameCmd.draw
                00005732: ^DrawContext.flush
                00027466: editorPutUi
                00028065: editorMain
                00028191: main
                00028194: <unknown>
```
Again, it only happens in the play mode under Windows.

**Comment by skejeton** [comment]
@vtereshkov I'm unable to reproduce it. Can you record a screencap?

**Comment by vtereshkov** [comment]
@skejeton I know where the problem is: `camera = d_rerp.iVf2(camera, props.pos, th.delta/100.0)`.

On Windows, the frames are not updated while the window is being resized. Therefore, at the first update after resizing, `th.delta` can be huge (i.e., equal to the total time of resizing), so that your interpolation in `d_rerp.iVf2()` fails. Fundamentally, this problem is very similar to the 'crazy text' issue we discussed before.

**Comment by skejeton** [comment]
@vtereshkov Hmm. Should the interpolation functions clamp the value?

**Comment by vtereshkov** [comment]
Of course your `delta/100.0` in `d_rerp.iVf2()` should be strictly less than 1, so you should clamp `delta` with something strictly less than 100.

**Comment by skejeton** [comment]
@vtereshkov I'll introduce d_global.safedt

**Comment by skejeton** [comment]
Hmm. I think it's better to clamp it in interpolation functions afterall.

**Comment by skejeton** [comment]
@vtereshkov I fixed that, check if issue persists.

**Comment by vtereshkov** [comment]
@skejeton It pesists in a slightly different fashion. I'm almost sure it's because you're ignoring the other instances of `th.delta`. In my experiments, I introduced a global clamped `delta`, and the issue went away.

**Comment by skejeton** [comment]
@vtereshkov this is weird. It shouldn't happen. Are you sure this is the latest version? Does the crash persist in same place? LMK

**Comment by vtereshkov** [comment]
@skejeton Not the crash, but the world gets distorted and then disppears.

![image](https://user-images.githubusercontent.com/52492460/191351147-3c8bb16f-40eb-424a-b8ac-9ff57793eb8c.png)

![image](https://user-images.githubusercontent.com/52492460/191351271-6b9c2bb3-bd50-4157-ad5c-a96ae94a85dd.png)

**Comment by skejeton** [comment]
@vtereshkov Hmm. Indeed. I think I'll hotfix it right now by clamping the th.delta to a certain value, like < 100. Because zipping through floors happens even to me, when the app is unfocused the delta spikes up a lot. There's 2 options I can see: Skip frames with high deltas, like over 120 is already borderline unplayable, or clamp the deltas. What do you think?

**Comment by skejeton** [comment]
I think clamping sounds reasonable. Either way that means deltas shouldn't be used to calculate any time in code, rightfully so.

**Comment by skejeton** [comment]
@vtereshkov done. Check it

**Comment by skejeton** [comment]
Oh right. I forgot to remove 9 fps limit I set. I'll invest some time into making an .env type thing for this project, because I don't wanna leave the game on with some debug values set.

**Comment by vtereshkov** [comment]
Perfect!
